### ISSUE TITLE
How to upload a new component to the web editor?

### ISSUE THREAD

**Issue by salwaElkaddaoui** [circuitdiagram/circuitdiagram#18]
I work under ubuntu 16.04 and I've been unable to use the CLI version of circuit-diagram (it keeps on crashing), I don't know whether it's possible to build circuit-diagram on ubuntu (it's an visual studio solution...), and when I downloaded the executable for windows (Setup.exe) and tried to install it on ubuntu 16.04 using wine, the installation was unsuccessful. I wrote the code for a new component and would like to add it to the web editor, how can I add new components to the web editor? (and by any chance, how can I build the source code of circuit-diagram on ubuntu 16.04?)

**Comment by SamuelFisher** [comment]
For Circuit Diagram CLI, what command are you trying to run? What does it output before exiting?

To add new components to the web editor, please raise a pull request on the [components repository](https://github.com/circuitdiagram/components).

Thanks
