### ISSUE TITLE
Web editor won't start

### ISSUE THREAD

**Issue by Peer-van-Altenborg** [circuitdiagram/circuitdiagram#20]
Hi,
Last week I tried several times to open the web editor, but it won't start. The message 'Getting ready...' is displayed, but nothing else happens. I'm on Windows 10 with Edge as browser. Please let me know if you need further information.
Kind regards,
Peer van Altenborg
The Netherlands

**Comment by SamuelFisher** [comment]
Please could you try using Chrome or Firefox? Let me know if there are any issues.

**Comment by Peer-van-Altenborg** [comment]
The web-editor starts in a normal way when I use Chrome or Firefox.
    Op donderdag 12 september 2019 22:08:21 CEST schreef Samuel Fisher <notifications@github.com>:  
 
 
Please could you try using Chrome or Firefox? Let me know if there are any issues.
