### ISSUE TITLE
display error on components options when importing 

### ISSUE THREAD

**Issue by papilinou** [circuitdiagram/circuitdiagram#27]
when importing from PC a cddx project, inductor value is set to show even when set to off when exporting,and toggle switch show closed even when set to open at export,external input same,set reverse when re-importing,but if exporting the project to png ,settings are ok on png export.
I think that when components are reloading in display, you don't take care to components options like "display value" "reversed" and so on but they still are in cddx file.

**Comment by SamuelFisher** [comment]
The problem may be that you are using different versions of these components in the Desktop version compared to the latest versions used in the Web Editor.

You can try replacing them with the latest versions that are available for download from here: https://www.circuit-diagram.org/components - however please be aware that these versions will not display icons in the toolbar in Circuit Diagram Desktop.

The installed versions to be replaced can normally be found under `C:\Program Files\Circuit Diagram\ext`. You can check the version of each component that is currently being used by opening `Tools -> Components` and comparing to the latest version available for download.

**Comment by papilinou** [comment]
i'am speaking about web editor not desktop.
Design on web editor,download(save) as cddx on PC and then importing the saved cddx never go through CD Desktop.
designing a circuit on web editor with only an inductor "show inductance" is set and a toggle switch "closed" is set.
In the saved cddx file document xml is always like:
See joined picture as code can't be added here ,options never change they are always "false".

![CDDX test options](https://user-images.githubusercontent.com/3898168/98686749-386ae580-2369-11eb-963d-ca8fa5aac590.JPG)

**Comment by papilinou** [comment]
same with component "multiplexer"  which use Property type "bool"
same with component op-amp

**Comment by SamuelFisher** [comment]
Ok, thank you for explaining this in more detail. The issue has now been fixed.
