### ISSUE TITLE
missing infos in DOCS

### ISSUE THREAD

**Issue by papilinou** [circuitdiagram/circuitdiagram#28]
In DOCS>Components>Render Options>Grid add : in Gitpod>File>Settings>open preferences>Circuit Diagram>set:
Diagram Show Grid
Render a grid behind the component.(shown in blue).
In DOCS>Components>Render Options>Debug Layout: add in Gitpod>File>preferences>Circuit Diagram>set:
Render component layout information Diagram Debug Layout.
In DOCS>Components>Finishing:> circuit-diagramcli component my_component.xml -o my_component.cdcom
miss "-" between diagram and cli.> circuit-diagram-cli component my_component.xml -o my_component.cdcom

**Comment by SamuelFisher** [comment]
Thanks for this. The docs page already says this which explains how to configure those options in GitPod:

> Configure the render options in GitPod by going to File -> Settings -> Open Preferences and opening the Circuit Diagram section.

The `circuit-diagram-cli` command on the _Finishing_ page has now been corrected.
