### ISSUE TITLE
Render components with specified conditions

### ISSUE THREAD

**Issue by miguelzaqui** [circuitdiagram/circuitdiagram#32]
When I try to render a component, it is displayed horizontally and with its default values. For example, suppose we try to render a component of type _source_ as a _battery_. The command to execute is like the following:

`circuit-diagram-cli component source.xml -c Battery -o source.png --autosize`

The image obtained is the following:

![source](https://user-images.githubusercontent.com/32533193/120605852-8a19b100-c41c-11eb-846c-77474ee2e663.png)

How could I do for example to render the component as NOT horizontal or changing the value of any of its properties?

**Comment by miguelzaqui** [comment]
I already found the information that solves my question: [https://www.circuit-diagram.org/news/2018/05/visual-studio-code-extension](url)

**Comment by MiguelZaqui** [comment]
I already found the information that solves my question: [https://www.circuit-diagram.org/news/2018/05/visual-studio-code-extension](url)

**Comment by MiguelZaqui** [comment]
I already found the information that solves my question: [https://www.circuit-diagram.org/news/2018/05/visual-studio-code-extension](url)
